### ISSUE TITLE
Reset button does not reset errors

### ISSUE THREAD

**Issue by Revku** [FattyIsKing/backpack-size-calculator#1]
When you click the `Reset` button, the errors do not reset.

I attach the screenshot below:
![image](https://github.com/FattyIsKing/backpack-size-calculator/assets/58880091/abf5410d-9e28-485c-b61c-c8d39e05428f)

**Comment by FattyIsKing** [comment]
Hello Patryk! I fixed a bug which you sent me. Thank you for your feedback :)
